<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="md-notes: private Markdown notes, organised your way.">
    <title>md-notes · Markdown, en orden</title>
    <link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">
    <style>
        :root{color-scheme:light dark;--bg:#f5f8fa;--paper:#fff;--glass:#ffffffc9;--ink:#15212a;--muted:#61717d;--line:#d9e3e9;--cyan:#09b9d0;--cyan-ink:#003c46;--violet:#7766e8;--shadow:0 22px 65px #2038491c}
        @media(prefers-color-scheme:dark){:root{--bg:#0c1216;--paper:#141e24;--glass:#141e24dc;--ink:#e9f3f6;--muted:#99abb5;--line:#2b3a43;--cyan:#3bd9e9;--cyan-ink:#00323a;--violet:#9c90ff;--shadow:0 22px 65px #00000066}}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{min-width:320px;margin:0;background:radial-gradient(circle at 6% 0%,color-mix(in srgb,var(--cyan) 18%,transparent),transparent 27rem),radial-gradient(circle at 96% 14%,color-mix(in srgb,var(--violet) 15%,transparent),transparent 30rem),var(--bg);color:var(--ink);font:16px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}.wrap{width:min(1120px,calc(100% - 40px));margin:auto}
        .nav{height:80px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:9px;font-weight:850;letter-spacing:-.04em;font-size:1.1rem}.spark{color:var(--cyan);font-size:1.5rem}.nav nav{display:flex;gap:25px;color:var(--muted);font-size:.9rem;font-weight:700}.nav nav a:hover{color:var(--ink)}.actions{display:flex;gap:10px}.button{min-height:42px;padding:0 16px;border:1px solid transparent;border-radius:10px;display:inline-flex;align-items:center;justify-content:center;background:var(--cyan);color:var(--cyan-ink);font-size:.89rem;font-weight:850;transition:.18s transform,.18s filter;box-shadow:0 8px 22px color-mix(in srgb,var(--cyan) 20%,transparent)}.button:hover{transform:translateY(-2px);filter:brightness(1.05)}.button.alt{background:transparent;border-color:var(--line);box-shadow:none;color:var(--ink)}.button.alt:hover{background:var(--glass)}
        .hero{padding:75px 0 98px;display:grid;grid-template-columns:1.02fr .98fr;align-items:center;gap:62px}.eyebrow{display:inline-flex;align-items:center;gap:8px;border:1px solid var(--line);border-radius:999px;padding:7px 11px;background:var(--glass);color:var(--muted);font-size:.77rem;font-weight:750}.dot{width:7px;height:7px;background:var(--cyan);border-radius:50%;box-shadow:0 0 0 4px color-mix(in srgb,var(--cyan) 17%,transparent)}h1{max-width:700px;margin:17px 0;font-size:clamp(2.8rem,6vw,5.45rem);line-height:.97;letter-spacing:-.08em}h1 em{font-style:normal;color:var(--cyan)}.lead{max-width:560px;margin:0;color:var(--muted);font-size:1.12rem}.hero-actions{display:flex;flex-wrap:wrap;gap:11px;margin-top:29px}.micro{margin:16px 0 0;color:var(--muted);font-size:.79rem}
        .app-preview{overflow:hidden;border:1px solid var(--line);border-radius:18px;background:var(--paper);box-shadow:var(--shadow);transform:rotate(1.2deg)}.app-bar{height:49px;display:flex;align-items:center;gap:7px;padding:0 16px;border-bottom:1px solid var(--line)}.traffic{width:9px;height:9px;border-radius:50%;background:#ed7770}.traffic+span{background:#efbd58}.traffic+span+span{background:#70c995}.filename{margin-left:7px;color:var(--muted);font:11px ui-monospace,SFMono-Regular,monospace}.app-body{min-height:382px;display:grid;grid-template-columns:142px 1fr}.tree{padding:14px 10px;border-right:1px solid var(--line);color:var(--muted);font-size:.71rem}.tree b,.tree span{display:block;padding:6px 8px;border-radius:5px}.tree b{color:var(--ink)}.tree .in{padding-left:19px}.tree .active{background:color-mix(in srgb,var(--cyan) 17%,transparent);color:var(--ink)}.note{padding:29px}.note small{font-family:ui-monospace,SFMono-Regular,monospace;color:var(--cyan)}.note h2{margin:9px 0 14px;font-size:1.65rem;letter-spacing:-.05em}.note p{color:var(--muted);font-size:.88rem}.checks{display:grid;gap:9px;margin-top:21px;font-size:.81rem}.check{display:flex;align-items:center;gap:8px}.tick{display:grid;place-items:center;width:18px;height:18px;border-radius:5px;background:color-mix(in srgb,var(--cyan) 18%,transparent);color:var(--cyan);font-size:.72rem}
        .band{padding:26px 0;border-block:1px solid var(--line);text-align:center;color:var(--muted);font-size:.9rem;font-weight:650}.band strong{color:var(--ink)}.section{padding:103px 0}.heading{max-width:670px;margin-bottom:42px}.heading h2,.workflow h2,.cta h2{margin:12px 0;font-size:clamp(2.05rem,4vw,3.12rem);line-height:1.02;letter-spacing:-.065em}.heading p,.workflow p{margin:0;color:var(--muted);font-size:1.03rem}
        .features{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.feature{min-height:222px;padding:24px;border:1px solid var(--line);border-radius:16px;background:var(--glass)}.icon{display:grid;place-items:center;width:39px;height:39px;margin-bottom:36px;border-radius:10px;background:color-mix(in srgb,var(--cyan) 16%,transparent);color:var(--cyan);font-size:1.1rem}.feature:nth-child(even) .icon{color:var(--violet);background:color-mix(in srgb,var(--violet) 16%,transparent)}.feature h3{margin:0 0 7px;font-size:1rem;letter-spacing:-.025em}.feature p{margin:0;color:var(--muted);font-size:.88rem}
        .workflow{display:grid;grid-template-columns:.9fr 1.1fr;gap:20px}.routine,.privacy{padding:34px;border:1px solid var(--line);border-radius:18px;background:var(--glass)}.steps{display:grid;gap:13px;margin-top:22px}.step{display:flex;gap:14px;padding:13px 0;border-bottom:1px solid var(--line)}.step:last-child{border:0}.number{display:grid;place-items:center;flex:0 0 28px;height:28px;border-radius:50%;background:var(--cyan);color:var(--cyan-ink);font-size:.77rem;font-weight:850}.step strong{font-size:.9rem}.step small{display:block;color:var(--muted);font-size:.8rem}.privacy{background:linear-gradient(135deg,color-mix(in srgb,var(--violet) 13%,var(--paper)),var(--glass))}.privacy h3{margin:14px 0 25px;font-size:clamp(1.65rem,3vw,2.35rem);line-height:1.05;letter-spacing:-.06em}.privacy-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.privacy-item{padding:14px;border:1px solid var(--line);border-radius:11px;background:color-mix(in srgb,var(--paper) 67%,transparent);font-size:.84rem;font-weight:750}.privacy-item small{display:block;margin-top:4px;color:var(--muted);font-size:.75rem;font-weight:500}
        .cta{margin-bottom:82px;padding:56px 30px;border-radius:21px;background:var(--ink);color:var(--bg);text-align:center;box-shadow:var(--shadow)}.cta h2{max-width:650px;margin:0 auto 13px}.cta p{max-width:530px;margin:0 auto 24px;color:color-mix(in srgb,var(--bg) 70%,transparent)}footer{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:26px 0 34px;border-top:1px solid var(--line);color:var(--muted);font-size:.8rem}footer .brand{color:var(--ink)}.github-link{display:inline-flex;align-items:center;gap:6px;color:var(--muted);font-weight:750}.github-link:hover{color:var(--cyan)}.github-link svg{width:16px;height:16px;fill:currentColor}
        @media(max-width:850px){.nav nav{display:none}.hero{grid-template-columns:1fr;gap:43px;padding:48px 0 70px}.app-preview{max-width:600px;transform:none}.features{grid-template-columns:repeat(2,1fr)}.workflow{grid-template-columns:1fr}}@media(max-width:560px){.wrap{width:min(100% - 28px,1120px)}.nav{height:68px}.nav .alt{display:none}.hero{padding-top:38px}.app-body{min-height:330px;grid-template-columns:104px 1fr}.tree{padding-inline:7px}.note{padding:22px 18px}.note h2{font-size:1.3rem}.features{grid-template-columns:1fr}.feature{min-height:176px}.icon{margin-bottom:19px}.section{padding:70px 0}.routine,.privacy{padding:24px}.privacy-grid{grid-template-columns:1fr}.cta{margin-bottom:52px;padding:42px 22px}footer{flex-direction:column}}
    </style>
</head>
<body>
    @php($es = app()->getLocale() === 'es')
    <header class="wrap nav">
        <a class="brand" href="{{ route('home') }}"><span class="spark">✦</span> md-notes</a>
        <nav aria-label="{{ $es ? 'Navegación principal' : 'Main navigation' }}"><a href="#features">{{ $es ? 'Funciones' : 'Features' }}</a><a href="#privacy">{{ $es ? 'Privacidad' : 'Privacy' }}</a></nav>
        <div class="actions">@auth <a class="button alt" href="{{ route('notes.index') }}">{{ $es ? 'Mis notas' : 'My notes' }}</a> @else <a class="button alt" href="{{ route('login') }}">{{ $es ? 'Entrar' : 'Log in' }}</a><a class="button" href="{{ route('register') }}">{{ $es ? 'Crear cuenta' : 'Create account' }}</a> @endauth</div>
    </header>
    <main>
        <section class="wrap hero">
            <div>
                <span class="eyebrow"><span class="dot"></span>{{ $es ? 'Tu espacio Markdown, sin ruido' : 'Your Markdown space, without the noise' }}</span>
                <h1>{!! $es ? 'Tus ideas, <em>en orden.</em>' : 'Your ideas, <em>in order.</em>' !!}</h1>
                <p class="lead">{{ $es ? 'md-notes reúne apuntes, clases y proyectos en un espacio privado, rápido y pensado para escribir en Markdown.' : 'md-notes brings classes, projects, and ideas together in a private, fast space made for writing in Markdown.' }}</p>
                <div class="hero-actions">@auth <a class="button" href="{{ route('notes.index') }}">{{ $es ? 'Abrir mi espacio' : 'Open my space' }} →</a> @else <a class="button" href="{{ route('register') }}">{{ $es ? 'Empezar ahora' : 'Get started' }} →</a><a class="button alt" href="{{ route('login') }}">{{ $es ? 'Ya tengo cuenta' : 'I already have an account' }}</a> @endauth</div>
                <p class="micro">{{ $es ? 'Archivos .md, imágenes y adjuntos. Todo bajo tu cuenta.' : '.md files, images, and attachments. All under your account.' }}</p>
            </div>
            <div class="app-preview" aria-label="md-notes preview"><div class="app-bar"><span class="traffic"></span><span class="traffic"></span><span class="traffic"></span><span class="filename">/Universidad/Redes/apuntes.md</span></div><div class="app-body"><aside class="tree"><b>▾ {{ $es ? 'Universidad' : 'University' }}</b><span class="in">▸ {{ $es ? 'Matemáticas' : 'Maths' }}</span><span class="in">▾ {{ $es ? 'Redes' : 'Networks' }}</span><span class="in active">　apuntes.md</span><span class="in">　práctica.md</span><span>▸ {{ $es ? 'Proyectos' : 'Projects' }}</span></aside><article class="note"><small># markdown</small><h2>{{ $es ? 'Redes · apuntes' : 'Networks · notes' }}</h2><p>{{ $es ? 'Una nota limpia para concentrarte en el contenido y no en la herramienta.' : 'A clean note to focus on the content, not the tool.' }}</p><div class="checks"><span class="check"><i class="tick">✓</i>{{ $es ? 'Carpetas arrastrables' : 'Draggable folders' }}</span><span class="check"><i class="tick">✓</i>{{ $es ? 'Historial de versiones' : 'Version history' }}</span><span class="check"><i class="tick">✓</i>{{ $es ? 'Enlaces para compartir' : 'Links to share' }}</span></div></article></div></div>
        </section>
        <div class="band"><div class="wrap">{!! $es ? 'Escribe en <strong>Markdown</strong>. Organiza a tu manera. Conserva el control.' : 'Write in <strong>Markdown</strong>. Organise your way. Keep control.' !!}</div></div>
        <section id="features" class="wrap section">
            <div class="heading"><span class="eyebrow">{{ $es ? 'Hecho para el día a día' : 'Made for everyday work' }}</span><h2>{{ $es ? 'Todo lo que necesitas para que las notas no se te escapen.' : 'Everything you need so your notes do not get away from you.' }}</h2><p>{{ $es ? 'Una interfaz directa para tomar apuntes en clase, documentar proyectos y encontrarlo todo después.' : 'A focused interface for class notes, project documentation, and finding everything later.' }}</p></div>
            <div class="features">
                <article class="feature"><div class="icon">⌘</div><h3>{{ $es ? 'Markdown con vista previa' : 'Markdown with preview' }}</h3><p>{{ $es ? 'Lee tus notas formateadas y pasa a editar cuando lo necesites.' : 'Read formatted notes and switch to editing only when you need it.' }}</p></article>
                <article class="feature"><div class="icon">↳</div><h3>{{ $es ? 'Ordena sin fricción' : 'Organise without friction' }}</h3><p>{{ $es ? 'Crea carpetas, subcarpetas y reordena notas o categorías arrastrando.' : 'Create folders and subfolders, then rearrange notes or categories by dragging.' }}</p></article>
                <article class="feature"><div class="icon">◴</div><h3>{{ $es ? 'Historial de versiones' : 'Version history' }}</h3><p>{{ $es ? 'Consulta, descarga o restaura hasta 50 versiones durante 7 días.' : 'View, download, or restore up to 50 versions for 7 days.' }}</p></article>
                <article class="feature"><div class="icon">⌁</div><h3>{{ $es ? 'Comparte con control' : 'Share with control' }}</h3><p>{{ $es ? 'Genera enlaces de una hora, un día, una semana o sin caducidad.' : 'Create links for one hour, one day, one week, or with no expiry.' }}</p></article>
                <article class="feature"><div class="icon">▧</div><h3>{{ $es ? 'Imágenes y adjuntos' : 'Images and attachments' }}</h3><p>{{ $es ? 'Pega imágenes desde el portapapeles y adjunta archivos de hasta 10 MB.' : 'Paste images from your clipboard and attach files up to 10 MB.' }}</p></article>
                <article class="feature"><div class="icon">⌁</div><h3>{{ $es ? 'También desde terminal' : 'Also from the terminal' }}</h3><p>{{ $es ? 'Sube notas .md con la API y un token personal, desde curl o tus scripts.' : 'Upload .md notes with the API and a personal token, from curl or your scripts.' }}</p></article>
            </div>
        </section>
        <section id="privacy" class="wrap section" style="padding-top:0"><div class="workflow"><div class="routine"><span class="eyebrow">{{ $es ? 'Una rutina sencilla' : 'A simple routine' }}</span><h2>{{ $es ? 'De la idea a una biblioteca que sí usas.' : 'From an idea to a library you actually use.' }}</h2><div class="steps"><div class="step"><span class="number">1</span><div><strong>{{ $es ? 'Crea una nota o carpeta' : 'Create a note or folder' }}</strong><small>{{ $es ? 'Desde el panel o con clic derecho.' : 'From the sidebar or with a right click.' }}</small></div></div><div class="step"><span class="number">2</span><div><strong>{{ $es ? 'Escribe, pega y adjunta' : 'Write, paste, and attach' }}</strong><small>{{ $es ? 'Markdown, imágenes y archivos en el mismo sitio.' : 'Markdown, images, and files in the same place.' }}</small></div></div><div class="step"><span class="number">3</span><div><strong>{{ $es ? 'Encuéntralo o compártelo' : 'Find it or share it' }}</strong><small>{{ $es ? 'Con una estructura clara y enlaces revocables.' : 'With a clear structure and revocable links.' }}</small></div></div></div></div><div class="privacy"><span class="eyebrow">{{ $es ? 'Privado por diseño' : 'Private by design' }}</span><h3>{{ $es ? 'Cada cuenta tiene su propio espacio de notas.' : 'Every account has its own notes space.' }}</h3><div class="privacy-grid"><div class="privacy-item">{{ $es ? 'Separación por usuario' : 'Per-user isolation' }}<small>{{ $es ? 'Ningún usuario ve las notas de otro.' : 'No user can view another user’s notes.' }}</small></div><div class="privacy-item">{{ $es ? '100 MB incluidos' : '100 MB included' }}<small>{{ $es ? 'Cuota personal para notas y archivos.' : 'Personal quota for notes and files.' }}</small></div><div class="privacy-item">{{ $es ? 'Backups automáticos' : 'Automatic backups' }}<small>{{ $es ? 'Copias locales y remotas programadas.' : 'Scheduled local and remote copies.' }}</small></div><div class="privacy-item">{{ $es ? 'Tema automático' : 'Automatic theme' }}<small>{{ $es ? 'Sigue la preferencia de tu sistema.' : 'Follows your system preference.' }}</small></div></div></div></div></section>
        <section class="wrap cta"><h2>{{ $es ? 'Un sitio tranquilo para todo lo que quieres recordar.' : 'A quiet place for everything you want to remember.' }}</h2><p>{{ $es ? 'Crea tu espacio privado y empieza con una nota de bienvenida lista para editar.' : 'Create your private space and start with a welcome note ready to edit.' }}</p>@auth<a class="button" href="{{ route('notes.index') }}">{{ $es ? 'Ir a mis notas' : 'Go to my notes' }} →</a>@else<a class="button" href="{{ route('register') }}">{{ $es ? 'Crear mi cuenta' : 'Create my account' }} →</a>@endauth</section>
    </main>
    <footer class="wrap"><a class="brand" href="{{ route('home') }}"><span class="spark">✦</span> md-notes</a><span>{{ $es ? 'Notas y apuntes en Markdown.' : 'Notes and study notes in Markdown.' }}</span><a class="github-link" href="https://github.com/mateodd1/md-notes" target="_blank" rel="noopener noreferrer" aria-label="{{ $es ? 'Ver el código de md-notes en GitHub' : 'View md-notes source code on GitHub' }}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2C6.48 2 2 6.58 2 12.23c0 4.52 2.87 8.35 6.84 9.7.5.1.68-.22.68-.49 0-.24-.01-1.04-.01-1.89-2.78.62-3.37-1.2-3.37-1.2-.46-1.2-1.11-1.51-1.11-1.51-.91-.64.07-.63.07-.63 1 .07 1.53 1.06 1.53 1.06.9 1.57 2.35 1.12 2.92.85.09-.67.35-1.12.64-1.38-2.22-.26-4.56-1.15-4.56-5.1 0-1.13.39-2.05 1.03-2.77-.1-.26-.45-1.31.1-2.73 0 0 .84-.28 2.75 1.06A9.3 9.3 0 0 1 12 6.87c.85 0 1.71.12 2.51.35 1.91-1.34 2.75-1.06 2.75-1.06.55 1.42.2 2.47.1 2.73.64.72 1.03 1.64 1.03 2.77 0 3.96-2.35 4.83-4.58 5.09.36.32.68.92.68 1.86 0 1.35-.01 2.44-.01 2.78 0 .27.18.59.69.49A10.25 10.25 0 0 0 22 12.23C22 6.58 17.52 2 12 2Z"/></svg>GitHub</a></footer>
</body>
</html>
