@foreach ($nodes as $node)
    @if ($node['type'] === 'folder')
        <details class="tree-folder" @if (!($node['collapsed'] ?? false) || (!empty($path) && str_starts_with($path, $node['path'].'/'))) open @endif data-context-type="folder" data-context-path="{{ $node['path'] }}" data-context-name="{{ $node['name'] }}" data-context-color="{{ $node['color'] ?? '' }}" data-context-collapsed="{{ ($node['collapsed'] ?? false) ? '1' : '0' }}" data-context-pinned="{{ ($node['pinned'] ?? false) ? '1' : '0' }}" @if (!empty($node['color'])) style="--folder-color:{{ $node['color'] }}" @endif>
            <summary draggable="true" data-drag-path="{{ $node['path'] }}" data-drag-type="folder" data-drop-path="{{ $node['path'] }}" data-folder-sort-target><x-icon name="chevron-right" class="tree-caret" /><x-icon name="folder" class="folder-icon" /><span class="tree-item-name">{{ $node['name'] }}</span>@if ($node['pinned'] ?? false)<span class="pin-indicator" title="{{ __('ui.pin') }}" aria-label="{{ __('ui.pin') }}"><x-icon name="pin" /></span>@endif<button class="tree-context-trigger" type="button" data-context-trigger aria-label="{{ __('ui.actions') }}" title="{{ __('ui.actions') }}"><x-icon name="more" /></button></summary>
            <div class="tree-children">@include('notes._tree', ['nodes' => $node['children'], 'path' => $path])</div>
        </details>
    @else
        <div class="tree-note {{ $path === $node['path'] ? 'active' : '' }}" draggable="true" data-drag-path="{{ $node['path'] }}" data-drag-type="note" data-context-type="note" data-context-path="{{ $node['path'] }}" data-context-name="{{ $node['name'] }}" data-context-pinned="{{ ($node['pinned'] ?? false) ? '1' : '0' }}"><a class="tree-note-link" href="{{ route('notes.show', ['path' => $node['path']]) }}"><x-icon name="file" class="tree-note-icon" /><span class="tree-item-name">{{ $node['name'] }}</span></a>@if ($node['pinned'] ?? false)<span class="pin-indicator" title="{{ __('ui.pin') }}" aria-label="{{ __('ui.pin') }}"><x-icon name="pin" /></span>@endif<button class="tree-context-trigger" type="button" data-context-trigger aria-label="{{ __('ui.actions') }}" title="{{ __('ui.actions') }}"><x-icon name="more" /></button></div>
    @endif
@endforeach
