@extends('layouts.app')

@push('head')
<link rel="stylesheet" href="{{ asset('assets/md-notes-workspace.css') }}?v={{ filemtime(public_path('assets/md-notes-workspace.css')) }}">
@endpush

@section('body')
<div class="workspace">
    <aside id="sidebar" class="sidebar">
        <header class="side-head"><a class="side-brand" href="{{ route('notes.index') }}">✦ md-notes</a><div class="side-actions"><a href="#new-folder" title="{{ __('ui.new_folder') }}"><button type="button">＋</button></a><a href="#new-note" title="{{ __('ui.new_note') }}"><button type="button">▤</button></a></div></header>
        <button id="open-note-search" class="note-search-button" type="button">⌕ {{ __('ui.search_notes') }} <kbd>Ctrl K</kbd></button>
        <div id="root-drop-target" class="root-drop-target" data-drop-path="" aria-label="{{ __('ui.root') }}">⌂ {{ __('ui.root') }}</div>
        <nav id="tree" class="tree" data-drop-path="" aria-label="{{ __('ui.notes') }}">@include('notes._tree', ['nodes' => $tree, 'path' => $path])</nav>
        <section id="storage-meter" class="storage-meter" aria-label="{{ __('ui.storage') }}"><div class="storage-meter-head"><span>{{ __('ui.storage') }}</span><strong>{{ $quota['used_human'] }} / {{ $quota['limit_human'] }}</strong></div><div class="storage-meter-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{{ $quota['percentage'] }}"><span style="width:{{ $quota['percentage'] }}%"></span></div></section>
    </aside>
    <div id="sidebar-backdrop" class="sidebar-backdrop" aria-hidden="true"></div>
    <main class="content">
        <header class="toolbar">
            <button id="mobile-notes-toggle" class="mobile-notes-toggle" type="button" aria-controls="sidebar" aria-expanded="false">☰ {{ __('ui.notes') }}</button>
            <div><h1>{{ $path ? $title : __('ui.your_notes') }}</h1>@if ($path)<div class="toolbar-sub">{{ $path }}</div>@endif</div>
            <div class="toolbar-actions">
                @if ($path)
                    <span id="save-state" class="save-state" hidden>{{ __('ui.saved') }}</span><a class="button danger small" href="#confirm-delete">{{ __('ui.delete') }}</a><button id="edit-note" class="button secondary small" type="button">{{ __('ui.edit') }}</button><button id="read-note" class="button secondary small" type="button" hidden>{{ __('ui.reading') }}</button><button id="save-note" form="note-form" class="button small" type="submit" hidden>{{ __('ui.save_note') }}</button>
                @endif
                <details class="profile-menu"><summary aria-label="Abrir menú de perfil"><span class="profile-avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name, 0, 1)) }}</span><span class="profile-name">{{ auth()->user()->name }}</span></summary><div class="profile-popover"><div class="profile-identity"><strong>{{ auth()->user()->name }}</strong><span>{{ auth()->user()->email }}</span></div><button type="button" class="profile-item" data-theme-choice="system">◐ {{ __('ui.system_theme') }}</button><button type="button" class="profile-item" data-theme-choice="light">☀ {{ __('ui.light_mode') }}</button><button type="button" class="profile-item" data-theme-choice="dark">☾ {{ __('ui.dark_mode') }}</button><div class="profile-separator"></div>@if (auth()->user()->isDemo())<span class="profile-item disabled" title="{{ __('ui.demo_settings_disabled') }}">⚙ {{ __('ui.profile_settings') }} (demo)</span>@else<a class="profile-item" href="{{ route('profile.edit') }}">⚙ {{ __('ui.profile_settings') }}</a>@endif<a class="profile-item" href="{{ route('shares.index') }}">↗ {{ __('ui.shared') }}</a><a class="profile-item" href="{{ route('trash.index') }}">♲ {{ __('ui.trash') }}</a><a class="profile-item" href="{{ route('documentation') }}">ⓘ {{ __('ui.documentation') }}</a><div class="profile-separator"></div><form method="post" action="{{ route('logout') }}">@csrf<button class="profile-item danger">⎋ {{ __('ui.logout') }}</button></form></div></details>
            </div>
        </header>
        @if ($errors->any()) <div class="errors workspace-errors"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif
        @if ($path)
            <div id="editor-layout" class="editor-layout is-reading"><section class="editor-pane"><form id="note-form" action="{{ route('notes.update', ['path' => $path]) }}" method="post">@csrf @method('PUT')<div class="format-toolbar" aria-label="{{ __('ui.markdown_format') }}"><button type="button" data-format="h1" title="{{ __('ui.heading') }}">H1</button><button type="button" data-format="h2" title="{{ __('ui.heading_2') }}">H2</button><button type="button" data-format="h3" title="H3">H3</button><button type="button" data-format="bold" title="{{ __('ui.bold_placeholder') }}"><strong>B</strong></button><button type="button" data-format="italic" title="{{ __('ui.italic_placeholder') }}"><em>I</em></button><button type="button" data-format="quote" title="{{ __('ui.quote') }}">❝</button><button type="button" data-format="bullet" title="{{ __('ui.list') }}">• {{ __('ui.list') }}</button><button type="button" data-format="ordered" title="{{ __('ui.numbered_list') }}">1. {{ __('ui.list') }}</button><button type="button" data-format="link" title="{{ __('ui.link') }}">{{ __('ui.link') }}</button><button type="button" data-format="code" title="{{ __('ui.code_placeholder') }}">&lt;/&gt;</button><button id="attach-file" type="button" title="{{ __('ui.attach_file') }}" aria-label="{{ __('ui.attach_file') }}">📎</button><input id="attachment-file" type="file" multiple hidden></div><textarea id="editor" name="content" aria-label="{{ __('ui.markdown_content') }}">{{ $content }}</textarea></form></section><article class="preview-pane"><div class="preview-document"><div class="preview-markdown">{!! $rendered !!}</div>@include('notes._attachments', ['attachments' => $attachments])</div></article></div>
        @else
            <section class="empty"><div class="empty-inner"><div style="font-size:38px">✦</div><h1>{{ __('ui.organised_notes') }}</h1><p>{{ __('ui.empty_notes_help') }}</p><a class="button" href="#new-note">{{ __('ui.create_file') }}</a></div></section>
        @endif
    </main>
</div>

@if (session('status')) <div id="toast" class="toast" role="status">{{ session('status') }}<button type="button" aria-label="{{ __('ui.close') }}">×</button></div> @endif
@include('notes._search')
<div id="new-folder" class="modal"><form class="modal-card" method="post" action="{{ route('folders.store') }}" autocomplete="off" data-create-form data-create-kind="folder">@csrf<h2>{{ __('ui.new_folder') }}</h2><p>{{ __('ui.folder_example') }}</p><label for="folder-name">{{ __('ui.folder_name') }}</label><input id="folder-name" name="name" required maxlength="80" autocomplete="off"><label for="folder-parent">{{ __('ui.inside') }}</label>@include('notes._parent-picker', ['nodes' => $tree, 'fieldId' => 'folder-parent', 'pickerId' => 'folder-parent-picker'])<div class="modal-footer"><a href="#">{{ __('ui.cancel') }}</a><button class="button">{{ __('ui.create_folder') }}</button></div></form></div>
<div id="new-note" class="modal"><form class="modal-card" method="post" action="{{ route('notes.store') }}" autocomplete="off" data-create-form data-create-kind="note">@csrf<h2>{{ __('ui.new_note') }}</h2><p>{{ __('ui.note_creation_help') }}</p><label for="note-name">{{ __('ui.note_title') }}</label><input id="note-name" name="name" required maxlength="80" autocomplete="off"><label for="note-parent">{{ __('ui.inside') }}</label>@include('notes._parent-picker', ['nodes' => $tree, 'fieldId' => 'note-parent', 'pickerId' => 'note-parent-picker'])<div class="modal-footer"><a href="#">{{ __('ui.cancel') }}</a><button class="button">{{ __('ui.create_note') }}</button></div></form></div>
@if ($path)<div id="confirm-delete" class="modal"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">{{ __('ui.delete_note_question') }}</h2><p>{{ __('ui.delete_note_help', ['title' => $title]) }}</p><div class="modal-footer"><a href="#">{{ __('ui.cancel') }}</a><form action="{{ route('notes.destroy', ['path' => $path]) }}" method="post">@csrf @method('DELETE')<button class="button danger" type="submit">{{ __('ui.delete_note') }}</button></form></div></section></div>@endif
<div id="context-menu" class="context-menu" role="menu" aria-label="{{ __('ui.actions') }}"><button type="button" data-context-action="new-folder">{{ __('ui.new_folder') }}</button><button type="button" data-context-action="new-note">{{ __('ui.new_note') }} .md</button><button type="button" data-context-action="share" data-context-note-only hidden>{{ __('ui.share_link') }}</button><div class="separator" data-context-item-only hidden></div><button type="button" data-context-action="pin" data-context-item-only hidden>{{ __('ui.pin') }}</button><button type="button" data-context-action="history" data-context-note-only hidden>{{ __('ui.version_history') }}</button><button type="button" data-context-action="properties" data-context-note-only hidden>{{ __('ui.properties') }}</button><button type="button" data-context-action="download" data-context-note-only hidden>{{ __('ui.download') }}</button><button type="button" data-context-action="pdf" data-context-note-only hidden>{{ __('ui.export_pdf') }}</button><button type="button" data-context-action="rename" data-context-item-only hidden>{{ __('ui.edit') }}</button><button type="button" class="danger" data-context-action="delete" data-context-item-only hidden>{{ __('ui.delete') }}</button></div>
<div id="rename-item" class="modal"><form class="modal-card" method="post" action="{{ route('items.rename') }}" autocomplete="off">@csrf @method('PATCH')<h2 id="rename-title">{{ __('ui.rename') }}</h2><p id="rename-description">{{ __('ui.choose_new_name') }}</p><input id="rename-path" type="hidden" name="path"><label for="rename-name">{{ __('ui.name') }}</label><input id="rename-name" name="name" required maxlength="80" autocomplete="off"><div id="folder-color-field" hidden><label>{{ __('ui.folder_color') }}</label><input id="folder-color" type="hidden" name="color"><div class="folder-colors" role="radiogroup" aria-label="{{ __('ui.folder_color') }}"><button class="folder-color-choice default" type="button" data-folder-color="" title="{{ __('ui.folder_color_default') }}" aria-label="{{ __('ui.folder_color_default') }}"></button><button class="folder-color-choice" type="button" data-folder-color="#0284c7" style="--folder-choice:#0284c7" aria-label="Azul"></button><button class="folder-color-choice" type="button" data-folder-color="#7c3aed" style="--folder-choice:#7c3aed" aria-label="Violeta"></button><button class="folder-color-choice" type="button" data-folder-color="#db2777" style="--folder-choice:#db2777" aria-label="Rosa"></button><button class="folder-color-choice" type="button" data-folder-color="#ea580c" style="--folder-choice:#ea580c" aria-label="Naranja"></button><button class="folder-color-choice" type="button" data-folder-color="#16a34a" style="--folder-choice:#16a34a" aria-label="Verde"></button><button class="folder-color-choice" type="button" data-folder-color="#64748b" style="--folder-choice:#64748b" aria-label="Gris"></button></div></div><div id="folder-collapsed-field" hidden><input type="hidden" name="collapsed" value="0"><label class="folder-collapse-option" for="folder-collapsed"><input id="folder-collapsed" type="checkbox" name="collapsed" value="1"> {{ __('ui.keep_folder_collapsed') }}</label></div><div class="modal-footer"><a href="#">{{ __('ui.cancel') }}</a><button class="button">{{ __('ui.save_name') }}</button></div></form></div>
<div id="confirm-delete-item" class="modal"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="item-delete-title"><h2 id="item-delete-title">{{ __('ui.delete_item_question') }}</h2><p id="item-delete-description">{{ __('ui.delete_item_help') }}</p><div class="modal-footer"><a href="#">{{ __('ui.cancel') }}</a><form method="post" action="{{ route('items.destroy') }}">@csrf @method('DELETE')<input id="item-delete-path" type="hidden" name="path"><button class="button danger" type="submit">{{ __('ui.delete') }}</button></form></div></section></div>
<div id="share-note" class="modal"><form class="modal-card" method="post" action="{{ route('shares.store') }}">@csrf<input id="share-path" type="hidden" name="path"><h2>{{ __('ui.share_note') }}</h2><p>{{ __('ui.share_help') }}</p><fieldset id="share-duration" class="duration-options"><legend>{{ __('ui.duration') }}</legend><label class="duration-choice"><input type="radio" name="duration" value="1h"><span>{{ __('ui.one_hour') }}</span></label><label class="duration-choice"><input type="radio" name="duration" value="24h" checked><span>{{ __('ui.twenty_four_hours') }}</span></label><label class="duration-choice"><input type="radio" name="duration" value="7d"><span>{{ __('ui.seven_days') }}</span></label><label class="duration-choice"><input type="radio" name="duration" value="forever"><span>{{ __('ui.never') }}</span></label></fieldset><div class="modal-footer"><a href="#">{{ __('ui.cancel') }}</a><button class="button">{{ __('ui.create_link') }}</button></div></form></div>
@if (session('share_url'))<div id="share-created" class="modal"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="share-created-title"><h2 id="share-created-title">{{ __('ui.shared_link') }}</h2><p>{{ session('share_expiration') }}</p><label for="share-url">{{ __('ui.link') }}</label><input id="share-url" value="{{ session('share_url') }}" readonly><div class="modal-footer"><a href="#">{{ __('ui.close') }}</a><button id="copy-share-url" class="button" type="button">{{ __('ui.copy_link') }}</button></div></section></div>@endif
<div id="version-history" class="modal"><section class="modal-card history-modal" role="dialog" aria-modal="true" aria-labelledby="history-title"><header class="history-modal-header"><div><h2 id="history-title">{{ __('ui.version_history') }}</h2><p id="history-path"></p></div></header><div id="history-content"><p>{{ __('ui.loading_versions') }}</p></div><div class="modal-footer"><a href="#">{{ __('ui.close') }}</a></div></section></div>
<div id="note-properties" class="modal"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="note-properties-title"><h2 id="note-properties-title">{{ __('ui.note_properties') }}</h2><p id="note-properties-path"></p><dl id="note-properties-content" class="properties-list"><dt>{{ __('ui.created_at') }}</dt><dd>{{ __('ui.loading_properties') }}</dd></dl><div class="modal-footer"><a href="#">{{ __('ui.close') }}</a></div></section></div>
<div id="pdf-viewer" class="modal"><section class="modal-card pdf-viewer-modal" role="dialog" aria-modal="true" aria-labelledby="pdf-viewer-title"><header class="pdf-viewer-header"><div><h2 id="pdf-viewer-title">{{ __('ui.pdf_viewer') }}</h2><p id="pdf-viewer-name"></p></div></header><div class="pdf-viewer-frame-wrap"><iframe id="pdf-viewer-frame" class="pdf-viewer-frame" title="{{ __('ui.pdf_viewer') }}" referrerpolicy="no-referrer"></iframe></div><p class="pdf-viewer-fallback">{{ __('ui.pdf_viewer_fallback') }} <a id="pdf-viewer-new-tab" href="#" target="_blank" rel="noopener noreferrer">{{ __('ui.open_new_tab') }}</a></p><div class="modal-footer"><a id="pdf-viewer-download" class="button secondary" href="#">{{ __('ui.download') }}</a><a href="#">{{ __('ui.close') }}</a></div></section></div>
<div id="confirm-restore-version" class="modal"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="restore-version-title"><h2 id="restore-version-title">{{ __('ui.restore_version_question') }}</h2><p id="restore-version-description">{{ __('ui.restore_version_help') }}</p><div class="modal-footer"><a href="#version-history">{{ __('ui.cancel') }}</a><form id="restore-version-form" method="post" action="">@csrf @method('PATCH')<button class="button" type="submit">{{ __('ui.restore') }}</button></form></div></section></div>

@php
    $workspaceTranslations = [
        'pdfPreparing' => __('ui.pdf_preparing'), 'pdfDownloaded' => __('ui.pdf_downloaded'), 'pdfExportFailed' => __('ui.pdf_export_failed'),
        'close' => __('ui.close'), 'newFolder' => __('ui.new_folder'), 'newSubfolder' => __('ui.new_subfolder'), 'newNote' => __('ui.new_note'), 'newNoteHere' => __('ui.new_note_here'),
        'renameFolder' => __('ui.rename_folder'), 'renameNote' => __('ui.rename_note'), 'renameFolderHelp' => __('ui.rename_folder_help'), 'renameNoteHelp' => __('ui.rename_note_help'),
        'deleteFolderQuestion' => __('ui.delete_folder_question'), 'deleteNoteQuestion' => __('ui.delete_note_question'), 'deleteFolderHelp' => __('ui.delete_folder_help', ['name' => ':name']), 'deleteNoteHelpContext' => __('ui.delete_note_help_context', ['name' => ':name']),
        'linkCopied' => __('ui.link_copied'), 'copySelectedLink' => __('ui.copy_selected_link'), 'loadingVersions' => __('ui.loading_versions'), 'restoreSpecificHelp' => __('ui.restore_version_specific_help', ['saved_at' => ':saved_at']),
        'allVersions' => __('ui.all_versions'), 'view' => __('ui.view'), 'download' => __('ui.download'), 'restore' => __('ui.restore'), 'noVersions' => __('ui.no_versions'), 'characters' => __('ui.characters'),
        'couldNotOpenVersion' => __('ui.could_not_open_note'), 'couldNotLoadHistory' => __('ui.could_not_open_note'), 'couldNotMove' => __('ui.could_not_move'), 'couldNotUpdateTree' => __('ui.could_not_update_tree'), 'itemMoved' => __('ui.item_moved'), 'noteReordered' => __('ui.note_reordered'), 'folderReordered' => __('ui.folder_reordered'), 'pin' => __('ui.pin'), 'unpin' => __('ui.unpin'),
        'couldNotSave' => __('ui.could_not_save'), 'couldNotRefreshPreview' => __('ui.could_not_refresh_preview'), 'changesSaved' => __('ui.changes_saved'), 'imageUploading' => __('ui.image_uploading'), 'imageUploaded' => __('ui.image_uploaded'), 'imageUploadFailed' => __('ui.image_upload_failed'), 'fileUploading' => __('ui.file_uploading'), 'fileUploaded' => __('ui.file_uploaded'), 'fileUploadFailed' => __('ui.file_upload_failed'), 'attachmentTooLarge' => __('ui.attachment_too_large'), 'couldNotOpenNote' => __('ui.could_not_open_note'), 'couldNotCreate' => __('ui.could_not_create_item'), 'saved' => __('ui.saved'), 'saving' => __('ui.saving'), 'unsavedChanges' => __('ui.unsaved_changes'), 'uploading' => __('ui.file_uploading'),
        'boldPlaceholder' => __('ui.bold_placeholder'), 'italicPlaceholder' => __('ui.italic_placeholder'), 'codePlaceholder' => __('ui.code_placeholder'), 'headingPlaceholder' => __('ui.heading_placeholder'), 'heading2Placeholder' => __('ui.heading_2_placeholder'), 'quotePlaceholder' => __('ui.quote_placeholder'), 'listItemPlaceholder' => __('ui.list_item_placeholder'), 'linkTextPlaceholder' => __('ui.link_text_placeholder'), 'downloadImage' => __('ui.download_image'), 'dropFiles' => __('ui.drop_files_to_attach'), 'createdAt' => __('ui.created_at'), 'markdownSize' => __('ui.markdown_size'), 'attachmentsSize' => __('ui.attachments_size'), 'totalSize' => __('ui.total_size'), 'attachmentsCount' => __('ui.attachments_count', ['count' => ':count']), 'loadingProperties' => __('ui.loading_properties'), 'couldNotLoadProperties' => __('ui.could_not_load_properties'),
    ];
@endphp
@include('notes._workspace-assets', ['workspaceTranslations' => $workspaceTranslations, 'path' => $path])
@endsection
