<article class="share-card">
    <div class="share-card-header"><div><h2><a href="{{ route('notes.show', ['path' => $share->path]) }}">{{ $share->path }}</a></h2><p class="share-details">@if ($share->expires_at){{ $isExpired ? __('ui.expired_on') : __('ui.expires') }} {{ $share->expires_at->isoFormat('L LT') }}@else {{ __('ui.does_not_expire') }} @endif</p></div><span class="share-state {{ $isExpired ? 'expired' : '' }}">{{ $isExpired ? __('ui.expired') : __('ui.active') }}</span></div>
    <div class="share-url-row"><input id="share-link-{{ $share->id }}" value="{{ $shareUrls[$share->id] }}" readonly aria-label="{{ __('ui.shared') }}"><button class="button secondary small" type="button" data-copy-share="share-link-{{ $share->id }}">{{ __('ui.copy') }}</button></div>
    <div class="share-actions">
        <form method="post" action="{{ route('shares.update', ['share' => $share]) }}">@csrf @method('PATCH')<fieldset class="share-duration"><legend>{{ __('ui.new_duration') }} <span class="label-help">({{ __('ui.from_now') }})</span></legend><label><input type="radio" name="duration" value="1h"><span>{{ __('ui.one_hour') }}</span></label><label><input type="radio" name="duration" value="24h" @checked(!is_null($share->expires_at))><span>{{ __('ui.twenty_four_hours') }}</span></label><label><input type="radio" name="duration" value="7d"><span>{{ __('ui.seven_days') }}</span></label><label><input type="radio" name="duration" value="forever" @checked(is_null($share->expires_at))><span>{{ __('ui.never') }}</span></label></fieldset><div class="share-form-footer"><button class="button small" type="submit">{{ __('ui.save_duration') }}</button></div></form>
        <a class="revoke-link" href="#revoke-share-{{ $share->id }}">{{ __('ui.revoke_link') }}</a>
    </div>
</article>
<div id="revoke-share-{{ $share->id }}" class="modal"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="revoke-title-{{ $share->id }}"><h2 id="revoke-title-{{ $share->id }}">{{ __('ui.revoke_question') }}</h2><p>{{ __('ui.revoke_help', ['path' => $share->path]) }}</p><div class="modal-footer"><a href="#">{{ __('ui.cancel') }}</a><form method="post" action="{{ route('shares.destroy', ['share' => $share]) }}">@csrf @method('DELETE')<button class="button danger" type="submit">{{ __('ui.revoke') }}</button></form></div></section></div>
